env:
  browser: true
  node: true
  es2021: true

extends:
  - 'plugin:vue/essential'
  - airbnb-base
  - plugin:import/typescript
  - '@vue/prettier'
  - 'plugin:prettier/recommended'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  sourceType: module

plugins:
  - vue
  - '@typescript-eslint'

settings:
  import/extensions:
    - .js
    - .ts
    
rules:
  prettier/prettier:
    - error
  vue/no-multiple-template-root:
    - off
  "import/extensions":
    - error
    - ignorePackages
    - ts: never