name: Oppskrift pull request validations

on:
  pull_request:
    branches:
      - main
    
env:
  cache-name: cache-node-modules

jobs:
  install:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
      
      - name: Use NodeJS 14 LTS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - run: yarn install --frozen-lockfile
      
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

  check_lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          
      - run: yarn lint
  
  check_tests:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          
      - run: yarn test
  
  check_build:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
      
      - run: yarn build
